routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([ 'verify' => true ]);

Route::redirect('/home', '/');

Route::get('/', 'HomeController@index')->name('home');

Route::resources([
    'creations' => 'CreationController',
    'sketches' => 'SketchController',
    'challenges' => 'ChallengeController',
]);

// Comments
Route::resource('comments', 'CommentsController')
    ->only([ 'store', 'destroy' ]);
Route::get('{commentable_type}/{commentable_id}#comment:{comment}')
    ->name('comments.show');

// Responses
Route::resource('responses', 'ResponseController')
    ->only([ 'show', 'store', 'edit', 'update', 'destroy' ]);
Route::get('challenges/{challenge}/responses/create', 'ResponseController@create')
    ->name('responses.create');

// Users
Route::resource('users', 'UserController')
    ->except([ 'show' ]);
Route::get('{user}/togglefollow', 'UserController@toggleFollow')
    ->middleware('auth')
    ->name('users.togglefollow');
Route::post('/validate-username', 'UserController@validateUsername')
    ->middleware('auth');
Route::get('/{user}/notifications', 'UserController@notifications')
    ->middleware('auth')
    ->name('users.notifications');

// Folders
Route::resource('folders', 'FolderController')
    ->except([ 'index' ]);

// Push Subscriptions
Route::put('push-subscription', 'PushSubscriptionController@update');
Route::delete('push-subscription', 'PushSubscriptionController@destroy');

// User
Route::get('/{user}', 'UserController@show')
    ->name('users.show');

app/Comment.php
<?php

namespace Artfamily;

use Balping\HashSlug\HasHashSlug;

class Comment extends Model
{
    use hasHas, hasRoutes, HasHashSlug;

    protected $fillable = [ 'body', 'user_id' ];

    public function routeParameters() {
        return [
            'id' => $this->id,
            'commentable_type' => optional($this->commentable)->routename(),
            'commentable_id' => optional($this->commentable)->getRouteKey(),
        ];
    }

    public function commentable() {
        return $this->morphTo();
    }

    public function user() {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace Artfamily\Http\Controllers;

use Artfamily\Comment;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Comment::class);
        $this->validate($request, [
            'commentable_type' => [ 'required', 'string', function($attribute, $value, $fail) {
                if(!$value::has('comments')) {
                    return $fail('This type of element is not commentable.');
                }
            } ],
            'commentable_id' => 'required|integer',
            'body' => 'required|string',
        ]);

        $comment = new Comment([ 'body' => $request->input('body') ]);
        $comment->commentable_type = $request->commentable_type;
        $comment->commentable_id = $request->commentable_id;

        if(!$comment->commentable) {
            return redirect()->back()->withErrors(['This element does not exist.'])->withInput();
        }

        $comment->user_id = auth()->id();
        $comment->save();
        return redirect()->back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Artfamily\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Artfamily\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $this->authorize('delete', $comment);

        $comment->delete();
        
        return redirect()->back();
    }
}

resources/views/comments/create.blade.php
<form class="flex flex-col md:flex-row items-center justify-stretch" method="POST" action="{{ route('comments.store') }}">
    @csrf
    <input type="hidden" name="commentable_type" value="{{ get_class($commentable) }}">
    <input type="hidden" name="commentable_id" value="{{ $commentable->id }}">
    <textarea name="body" placeholder="{{ __('Awesome!') }}" rows="1" class="input bg-grey-lightest rounded p-4 md:mr-4 mt-0 growing" value="{{ old('body') }}"></textarea>
    <button type="submit" class="button self-end md:self-auto mt-4 md:mt-0">
        {{ __('Comment') }}
    </button>
</form>

resources/views/comments/list.blade.php
@foreach ($comments as $comment)
    
    <div id="comment:{{ $comment->id }}" class="flex flex-row items-start justify-start -mx-8 px-8 py-4">
        <img src="{{ $comment->user->avatar()->url() }}" alt="" class="rounded-full h-12">
        <div class="ml-4">
            <div class="flex flex-row flex-wrap md:flex-no-wrap items-center justify-start mb-2">
                <a href="{{ $comment->user->route() }}" class="font-bold link text-black">
                    {{ $comment->user->name }}
                </a>
                <span class="text-grey-darkest font-light ml-4">
                    {{ $comment->updated_at->diffForHumans() }}
                </span>
                @can('delete', $comment)
                    <form action="{{ $comment->route('destroy') }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="text-red ml-8 flex flex-row items-center justify-center text-sm">
                            <i class="mi mi-Delete mr-2"></i>
                            {{ __('Delete') }}
                        </button>
                    </form>
                @endcan
            </div>
            <div class="">
                {!! nl2br(e($comment->body)) !!}
            </div>
            {{-- <div class="text-grey-darkest font-light text-sm mt-2 flex flex-row justify-start items-center">
                @if($comment->comments->count() > 0)
                    <div class="font-bold cursor-pointer mr-2">
                        {{ __('Show Responses') }} ({{ $comment->comments->count() }})
                    </div>
                @endif
                @can('create', Artfamily\Comment::class)
                    @if($comment->comments->count() > 0)
                        <div class="mr-2">
                            &bull;
                        </div>
                    @endif
                    <div class="cursor-pointer">
                        {{ __('Reply') }}
                    </div>
                @endcan
            </div> --}}
        </div>
    </div>
    {{-- <div class="ml-6 mt-4 border-grey border-l-2 p-4 {{ $comment->comments->count() > 0 ? '' : 'hidden' }}">
        <div class="mb-8 text-sm">
            @include('comments.create', [ 'commentable' => $comment ])
        </div>
        @include('comments.list', [ 'comments' => $comment->commentsSorted() ])
    </div> --}}

@endforeach