routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([ 'verify' => true ]);

Route::redirect('/home', '/');

Route::get('/', 'HomeController@index')->name('home');

Route::resources([
    'creations' => 'CreationController',
    'sketches' => 'SketchController',
    'challenges' => 'ChallengeController',
]);

// Comments
Route::resource('comments', 'CommentsController')
    ->only([ 'store', 'destroy' ]);
Route::get('{commentable_type}/{commentable_id}#comment:{comment}')
    ->name('comments.show');

// Responses
Route::resource('responses', 'ResponseController')
    ->only([ 'show', 'store', 'edit', 'update', 'destroy' ]);
Route::get('challenges/{challenge}/responses/create', 'ResponseController@create')
    ->name('responses.create');

// Users
Route::resource('users', 'UserController')
    ->except([ 'show' ]);
Route::get('{user}/togglefollow', 'UserController@toggleFollow')
    ->middleware('auth')
    ->name('users.togglefollow');
Route::post('/validate-username', 'UserController@validateUsername')
    ->middleware('auth');
Route::get('/{user}/notifications', 'UserController@notifications')
    ->middleware('auth')
    ->name('users.notifications');

// Folders
Route::resource('folders', 'FolderController')
    ->except([ 'index' ]);

// Push Subscriptions
Route::put('push-subscription', 'PushSubscriptionController@update');
Route::delete('push-subscription', 'PushSubscriptionController@destroy');

// User
Route::get('/{user}', 'UserController@show')
    ->name('users.show');

app/Folder.php
<?php

namespace Artfamily;

use Balping\HashSlug\HasHashSlug;

class Folder extends Model
{
    use hasRoutes, HasHashSlug;
    
    public static $icons = [ 'checkmark', 'image', 'heart', 'home', 'pencil' ];

    protected $fillable = [ 'name', 'icon', 'user_id' ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function creations()
    {
        return $this->morphedByMany(Creation::class, 'foldable');
    }

    public function sketches()
    {
        return $this->morphedByMany(Sketch::class, 'foldable');
    }

    public function images($limit = null) 
    {
        return $this->imagables()->map(function($item) {
            return $item->image;
        });
    }

    public function imagables() {
        $folder = $this;
        return Imagable::all()->filter(function($element) use ($folder) {
            return $element->folders->contains($folder);
        });
    }
}

app/Http/Controllers/FolderController.php
<?php

namespace Artfamily\Http\Controllers;

use Artfamily\Folder;
use Illuminate\Http\Request;

class FolderController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Folder::class);

        return view('folders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Folder::class);

        $request->validate([
            'name' => 'required|string',
            'icon' => 'nullable|string'
        ]);

        auth()->user()->folders()->create($request->all());
        
        return redirect()->route('users.show', ['id' => auth()->id()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \Artfamily\Folder  $folder
     * @return \Illuminate\Http\Response
     */
    public function show(Folder $folder)
    {
        return view('folders.show', compact('folder'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Artfamily\Folder  $folder
     * @return \Illuminate\Http\Response
     */
    public function edit(Folder $folder)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Artfamily\Folder  $folder
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Folder $folder)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Artfamily\Folder  $folder
     * @return \Illuminate\Http\Response
     */
    public function destroy(Folder $folder)
    {
        //
    }
}

resources/views/folders/create.blade.php
@extends('layouts.app')

@section('header')
    {{ __('New folder') }}
@endsection

@section('content')

    @include('components.errors')

    <form class="ui form" method="POST" action="{{ route('folders.store') }}">
        @csrf

        <div class="ui segment">
            <h4 class="ui horizontal divider header">
                {{ __('Create your folder') }}
            </h4>
    
            <div class="{{ $errors->has('name') ? 'error' : '' }} field">
                <label> {{ __('Name of your folder') }} </label>
                <input type="text" name="name" value=" {{ old('name') }} ">
            </div>

            <div class="{{ $errors->has('icon') ? 'error' : '' }} field">
                <label> {{ __('Choose an icon for your folder') }} </label>
                <div class="ui search selection dropdown">
                    <input name="icon" type="hidden" value="{{ old('icon') }}">
                    <i class="dropdown icon"></i>
                    <div class="default text">{{ __('Choose Icon') }}</div>
                    
                    <div class="menu">
                        @foreach (\Artfamily\Folder::$icons as $icon)
                            <div class="item" data-value="{{ $icon }}">
                                <i class="{{ $icon }} icon"></i>{{ $icon }}
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>

        @component('components.form.actions')
            {{ __('Create folder') }}
        @endcomponent

    </form>

@endsection

resources/views/folders/show.blade.php
@extends('layouts.app')

@section('header')
    {{ __('Folder') }}
@endsection

@section('background', 'white')

@section('padding', 'px-2')

@section('content')

<div class="three-container">

    <div class="left clearfix">

            <div class="md:card md:float-left md:bg-grey-darkest md:text-white mx-4 my-8 text-center font-black text-grey-darkest text-xl flex flex-row md:flex-col items-center justify-center"> 
                <i class="mi mi-Folder mr-4 md:mr-0 md:mb-8"></i>
                {{ $folder->name }}
            </div>

    </div>

    <div class="right buttons">

        @can('insert', $folder)
            <a href="{{ route('creations.create', [ 'folder' => $folder ]) }}" class="mt-8 button">
                {{ __('Upload creation') }}
            </a>
            <a href="{{ route('sketches.create', [ 'folder' => $folder ]) }}" class="mt-8 button">
                {{ __('Upload sketch') }}
            </a>
        @endcan

    </div>

    <div class="center">

        @include('components.imagables', ['imagables' => $folder->imagables()])

    </div>

</div>

    {{-- <div class="ui clearing segment">
        <h4 class="ui horizontal divider header">
            {{ __('Folder ') . $folder->name }}
        </h4>

        @can('insert', $folder)
            <a href="{{ route('creations.create', [ 'folder' => $folder ]) }}" class="ui primary right floated button">
                <i class="plus icon"></i>
                {{ __('Upload creation to this folder') }}
            </a>
        @endcan
    </div>

    @if (count($folder->creations))
        <h4 class="ui horizontal divider header">
            {{ __('Creations') }}
        </h4>
        @include('components.imagables', [ 'imagables' => $folder->creations ])
    @endif

    @if (count($folder->sketches))
        <h4 class="ui horizontal divider header">
            {{ __('Sketches') }}
        </h4>
        @include('components.imagables', [ 'imagables' => $folder->sketches ])
    @endif --}}

@endsection