routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([ 'verify' => true ]);

Route::redirect('/home', '/');

Route::get('/', 'HomeController@index')->name('home');

Route::resources([
    'creations' => 'CreationController',
    'sketches' => 'SketchController',
    'challenges' => 'ChallengeController',
]);

// Comments
Route::resource('comments', 'CommentsController')
    ->only([ 'store', 'destroy' ]);
Route::get('{commentable_type}/{commentable_id}#comment:{comment}')
    ->name('comments.show');

// Responses
Route::resource('responses', 'ResponseController')
    ->only([ 'show', 'store', 'edit', 'update', 'destroy' ]);
Route::get('challenges/{challenge}/responses/create', 'ResponseController@create')
    ->name('responses.create');

// Users
Route::resource('users', 'UserController')
    ->except([ 'show' ]);
Route::get('{user}/togglefollow', 'UserController@toggleFollow')
    ->middleware('auth')
    ->name('users.togglefollow');
Route::post('/validate-username', 'UserController@validateUsername')
    ->middleware('auth');
Route::get('/{user}/notifications', 'UserController@notifications')
    ->middleware('auth')
    ->name('users.notifications');

// Folders
Route::resource('folders', 'FolderController')
    ->except([ 'index' ]);

// Push Subscriptions
Route::put('push-subscription', 'PushSubscriptionController@update');
Route::delete('push-subscription', 'PushSubscriptionController@destroy');

// User
Route::get('/{user}', 'UserController@show')
    ->name('users.show');

app/Imagable.php
<?php

namespace Artfamily;

class Imagable {
    protected static $models = [
        Creation::class,
        Sketch::class,
    ];

    public static function all() {
        return self::get();
    }

    public static function query($query) {
        return self::get([ 'query' => $query ]);
    }

    public static function get($config = []) {
        $ret = collect();
        foreach(self::$models as $model) {
            $elements = $model::all();
            if(array_key_exists('query', $config)) {
                $elements = $config['query']->call($elements);
            }
            $ret = $ret->concat($elements);
        }
        return $ret;
    }
}

app/Response.php
<?php

namespace Artfamily;

use Balping\HashSlug\HasHashSlug;

class Response extends Model
{
    use hasHas, hasImage, hasRoutes, HasHashSlug, hasCaption, hasComments;

    public static $hasCaptionLink = true;
    public static $hasComputedCaption = true;

    protected $fillable = [ 'description', 'user_id', 'challenge_id' ];

    public function getCaptionAttribute() {
        return $this->challenge->caption;
    }

    public function getCaptionLinkAttribute() {
        return $this->challenge->route();
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function challenge() {
        return $this->belongsTo(Challenge::class);
    }
}

app/Http/Controllers/Imagable/Stores.php
<?php

namespace Artfamily\Http\Controllers\Imagable;

trait Stores {
    
}

app/Http/Controllers/ImagableController.php
<?php

namespace Artfamily\Http\Controllers;

use Artfamily\Creation;
use Artfamily\Image;
use Illuminate\Http\Request;
use Artfamily\Folder;

class ImagableController extends Controller
{
    public function viewName() {
        return 'imagables';
    }

    public function view($name, $data) {
        return view()->first([$this->viewName() . '.' . $name, 'imagables.' . $name], $data)->with('model', $this->model());
    }

    public function model() {
        return (object) [
            'name' => strtolower( str_singular( class_basename( $this->model ) ) ),
            'Name' => title_case( str_singular( class_basename( $this->model ) ) ),
            'names' => strtolower( str_plural( class_basename( $this->model ) ) ),
            'Names' => title_case( str_plural( class_basename( $this->model ) ) ),
            'route' => snake_case( str_plural( class_basename( $this->model ) ) ),
            'static' => $this->model,
        ];
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->view('index', [
            'imagables' => $this->model::latest()->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('create', $this->model);

        $belonging = $this->getBelonging();

        $data = [ 
            'imagable' => null,
        ];
        
        if($belonging->belongs) {
            $data['belonging'] = (object) [
                'key' => $belonging->key,
                'value' => $request->route($belonging->route)->id,
            ];
        }

        return $this->view('create', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  $imagable
     * @return \Illuminate\Http\Response
     */
    public function show($imagable)
    {
        return $this->view('show', [
            'imagable' => $imagable,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', $this->model);

        $belonging = $this->getBelonging();

        $rules = [
            'caption' => ($this->model::has('caption') && !$this->model::has('ComputedCaption') ? 'required' : 'nullable') . '|string|max:255',
            'description' => 'nullable|string',
            'folders' => 'nullable|string',
            'image' => ($this->model::has('image') && $this->isImageRequired() ? 'required|' : '') . Image::$restrictions
        ];

        if($belonging->belongs) {
            $rules[$belonging->key] = 'required|integer|exists:' . $belonging->tablename . ',id';
        }

        $request->validate($rules);

        $imagable = new $this->model([
            'user_id' => auth()->id(),
            'caption' => request('caption'),
            'description' => request('description'),
        ]);
        if($belonging->belongs) {
            $imagable->{$belonging->key} = request($belonging->key);
        }
        $this->callIfExists('beforeImagableSave', $imagable);
        $imagable->save();

        if($this->model::has('folders')) {
            $imagable->folders()->sync($this->foldersFromString($request->input('folders')));
        }

        if($this->model::has('image') && $request->has('image')) {
            $image = new Image();
            $image->imagable()->associate($imagable);
            $image->setImage($request->file('image'));
            $image->save();
        }

        return $this->redirectStore($imagable);
    }

    public function redirectStore($imagable) {
        return redirect()->route($this->model()->route . '.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  $imagable
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $imagable)
    {
        $this->authorize('update', $imagable);

        $belonging = $this->getBelonging();

        $data = [ 
            'imagable' => $imagable,
        ];
        
        if($belonging->belongs) {
            $data['belonging'] = (object) [
                'key' => $belonging->key,
                'value' => $imagable->{$belonging->key},
            ];
        }

        return $this->view('create', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  $imagable
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $imagable)
    {
        $this->authorize('update', $imagable);

        $belonging = $this->getBelonging();

        $rules = [
            'caption' => ($this->model::has('caption') && !$this->model::has('ComputedCaption') ? 'required' : 'nullable') . '|string|max:255',
            'description' => 'nullable|string',
            'folders' => 'nullable|string',
            'image' => 'nullable|' . Image::$restrictions
        ];

        if($belonging->belongs) {
            $rules[$belonging->key] = 'required|integer|exists:' . $belonging->tablename . ',id';
        }
        
        $validated = $request->validate($rules);

        if($this->model::has('image') && $request->file('image')) {
            $imagable->image->setImage($request->file('image'));
        }

        $imagable->fill($request->all());
        
        $imagable->save();

        if($this->model::has('folders')) {
            $imagable->folders()->sync($this->foldersFromString($request->input('folders')));
        }

        return redirect()->route($this->model()->route . '.show', compact('imagable'));
    }

    public static function foldersFromString($string) {
        if(!strlen($string)) {
            return [];
        }
        $folders = explode(',', $string);
        foreach($folders as $folder) {
            $folder = intval($folder);
        }
        return $folders;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  $imagable
     * @return \Illuminate\Http\Response
     */
    public function destroy($imagable)
    {
        $this->authorize('delete', $imagable);

        if($this->model::has('image')) {
            $imagable->image->delete();
        }
        $imagable->delete();
        return $this->redirectDestroy();
    }

    public function redirectDestroy() {
        return redirect()->route($this->model()->route . '.index');
    }

    public function isImageRequired() {
        return true;
    }

    public function getBelonging() {
        $belonging = $this->callIfExists('belonging');
        $belonging_key = snake_case(str_singular(class_basename($belonging))) . '_id';
        $belonging_db_name = snake_case(str_plural(class_basename($belonging)));

        return (object) [
            'belongs' => $belonging  ? true : false,
            'key' => $belonging_key,
            'tablename' => $belonging_db_name,
            'route' => snake_case(str_singular(class_basename($belonging))),
        ];
    }

    public function callIfExists($name, ...$args) {
        if(method_exists($this, $name)) {
            return $this->$name(...$args);
        }
        return null;
    }
}

resources/views/imagables/collection.blade.php
{{-- <div class="ui equal width grid">

    @foreach(rowify($images->take(9), 3) as $imagerow)
        <div class="row">

            @foreach ($imagerow as $image)
                <div class="column">
                    <img data-src="{{ $image->url() }}" class="ui tiny rounded image lazyload cui-square-image">
                </div>
            @endforeach

        </div>
    @endforeach

</div> --}}

<div class="cui-collection-grid">

    @foreach($images as $image)
        <img data-src="{{ $image->url() }}" class="lazyload cui-square-image">
    @endforeach

</div>

resources/views/imagables/create.blade.php
@extends('layouts.app')

@section('header')
    {{ __( ($imagable ? 'Update ' : 'New ') . $model->name) }}
@endsection

@section('content')

    @include('components.errors')

    <form method="POST" action="{{ $imagable ? route($model->route . '.update', compact('imagable')) : route($model->route . '.store') }}" class="three-container three-container-between" enctype="multipart/form-data">
        @csrf
        @if ($imagable)
            @method('PUT')
        @endif

        @if(isset($belonging))
            <input type="hidden" name="{{ $belonging->key }}" value="{{ $belonging->value }}">
        @endif

        @if($model->static::has('image') || $model->static::has('images'))
            <div class="left">
                <div class="card rounded-lg mx-auto mb-8 md:mb-0 w-48 h-48 picture-input text-grey-darkest font-light text-xl flex flex-col items-center justify-around text-center">
                    <i class="mi mi-Camera mi-2x"></i>
                    @if($model->static::has('image'))
                        {{ __('Choose a Picture') }}
                    @else
                        {{ __('Choose Pictures') }}
                    @endif
                    <input type="file" accepts='image/*' value="{{ old('image') }}" class="hidden" 
                        @if ($model->static::has('images'))
                            multiple
                            name="image[]"
                        @else
                            name='image'
                        @endif
                    >
                </div>
            </div>
        @endif

        <div class="center">
            @if ($model->static::has('caption') && !$model->static::has('ComputedCaption'))
                <div class="{{ $errors->has('caption') ? 'error' : '' }} card md:max-w-md md:mx-auto field">
                    <label class="font-light"> {{ __('Caption') }} </label>
                    <input class="input text-2xl font-black text-grey-darkest" type="text" name="caption" placeholder="{{ __('My awesome') }} {{ __($model->name) }}" value="{{ old('caption') ?: $imagable ? $imagable->caption : null }}" autofocus>
                </div>
            @endif

            <div class="{{ $errors->has('description') ? 'error' : '' }} card md:max-w-md md:mx-auto field">
                <label> {{ __('Description') }} </label>
                <textarea class="input" name="description" rows="5" placeholder="{{ __('It took me 5 hours to paint something amazing like this!') }}">{{ old('description') ?? $imagable ? $imagable->description : null }}</textarea>
            </div>

            {{-- @if ($model->static::has('folders'))
                <div class="card max-w-md mx-auto field">
                    <label>
                        {{ __('Folders') }}
                    </label>
                    <div class="flex flex-row items-center justify-start -ml-2 mt-4 folder-select">
                        @foreach (Auth::user()->folders as $folder)
                            <div class="folder-tag" data-id="{{ $folder->id }}">
                                <i class="mi mi-Folder mr-2"></i>
                                {{ $folder->name }}
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif --}}
        </div>

        <div class="right">
            <button type="submit" class="my-4 md:my-0 float-right button">
                {{ __( ($imagable ? 'Update ' : 'Publish ') . $model->name) }}
            </button>
        </div>

    </form>

@endsection

resources/views/imagables/index.blade.php
@extends('layouts.app')

@section('header')
    {{ __($model->Names) }}
@endsection

@section('background', 'white')

@section('content')

    <div class="three-container">
        <div class="center mx-8 md:mx-0">
            @include('components.imagables', ['imagables' => $imagables])
        </div>
        <div class="right clearfix">
            <a href="{{ route($model->route . '.create') }}" class="button float-right mt-8 mr-8 md:mr-4 md:mt-32">
                New {{ $model->Name }}
            </a>
        </div>
    </div>
    
    {{-- <div class="ui clearing segment">
        <h4 class="ui horizontal divider header"> {{ __('Actions') }} </h4>

        <a href="{{ route($model->route . '.create') }}" class="ui primary right floated button">
            <i class="plus icon"></i>
            {{ __('New ' . $model->name) }}
        </a>        
    </div> --}}

    {{-- @include('components.imagables', compact('imagables')) --}}

@endsection

resources/views/imagables/show.blade.php
@extends('layouts.app')

@section('header')
    {{ $model->Name }}
@endsection

@section('padding', 'px-0')

@section('content')

<div class="three-container three-container-between md:mt-8">

    @can('update', $imagable)
        <div class="right buttons mr-8">
            <a href="{{ $imagable->route('edit') }}" class="button-blue border-none mt-8 md:mt-0">
                <i class="mi mi-Edit mr-4"></i>
                {{ __('Edit') }}
            </a>
            <form action="{{ $imagable->route('destroy') }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="button-red border-none mt-8">
                    <i class="mi mi-Delete mr-4"></i>
                    {{ __('Delete') }}
                </button>
            </form>
        </div>
    @endcan

    <div class="center flex flex-col items-center md:px-8">

        <img data-src="{{ $imagable->image->big() }}" alt="" class="lazyload mx-auto md:rounded-lg z-10" style="max-height: 80vh">

        <div class="card self-stretch md:mt-8">
            <div class="flex flex-row justify-start items-center text-grey-darkest mb-8">
                <img data-src="{{ $imagable->user->avatar()->url() }}" alt="" class="lazyload h-12 rounded-full">
                <div class="flex flex-col justify-start items-start ml-4">
                    @if ($imagable->has('CaptionLink'))
                        <a href="{{ $imagable->caption_link }}" class="link font-black text-3xl">
                            {{ $imagable->caption }} 
                        </a>
                    @else
                        <div class="font-black text-3xl">
                            {{ $imagable->caption }} 
                        </div>
                    @endif
                    <div class="font-light text-center ">
                    {{ __('by') }} <a class="link" href="{{ $imagable->user->route() }}">{{ $imagable->user->name }}</a>
                    </div>
                </div>
            </div>
            @if ($imagable->description)
                {!! nl2br(e($imagable->description)) !!}
            @endif
            <div class="-mb-8 -mx-8 border-t-2 border-grey-lightest mt-8">
                <a href="{{ $imagable->image->full() }}" class="transition border-r-2 border-grey-lightest px-8 py-4 text-sm text-grey-darker font-bold inline-flex flex-row items-center hover:bg-black hover:text-white" download>
                    <i class="mi mi-Download mr-2"></i> Download full image
                </a>
            </div>
        </div>
    </div>

</div>

@if($imagable->has('comments'))
<div class="bg-white shadow-lg mt-16">
    <div class="three-container">

        <div class="center p-8">
            
            <div class="font-black text-grey-darkest">
                {{ __('Comments') }}
            </div>
            <div class="mt-4">
                <div class="mb-8">
                    @include('comments.create', [ 'commentable' => $imagable ])
                </div>
                @include('comments.list', [ 'comments' => $imagable->commentsSorted() ])
            </div>
    
        </div>
    
    </div>
</div> 
@endif

{{-- <div class="ui stackable grid">
    <div class="row">

        <div class="left floated ten wide column">
            <img class="ui centered rounded image cui-fullsize-imagable" src="{{ $imagable->image->url() }}" alt="">
        </div>

        <div class="right floated six wide stretched column">
            <div class="ui segment">
                <h4 class="ui horizontal divider header">{{ __('More from') }} {{ $imagable->user->name }}</h4>
                @include('imagables.collection', [ 'images' => $imagable->user->images() ])
            </div>
        </div>

    </div>
    <div class="row">
        <div class="sixteen wide column">
            <div class="ui segment">
                @include('components.user', [ 'user' => $imagable->user ])

                @if ($imagable->description)
                    <div class="ui list">
                        <div class="item">
                            <i class="grey bold icon"></i>
                            <div class="content">
                                <div class="description">
                                    {{ $imagable->description }}
                                </div>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div> --}}
        {{-- <div class="ui card">
            <div class="center aligned content">
                <div class="header">
                    {{ $imagable->caption }}
                </div>
            </div>
            <div class="center aligned content">
                <div class="meta">
                    <i class="clock icon"></i> {{ $imagable->created_at->diffForHumans() }}
                </div>
            </div>
            @if ($imagable->description)
                <div class="center aligned content">
                    <div class="description">
                        {!! nl2br(e($imagable->description)) !!}
                    </div>
                </div>
            @endif
            <a href="{{ route('users.show', $imagable->user) }}" class="extra content">
                <div class="center aligned author">
                    <img class="ui avatar image" src="{{ asset('/pictures/logo.png') }}"> {{ $imagable->user->name }}
                </div>
            </a>
            @can('update', $imagable)
                <div class="ui bottom attached buttons">
                    <a href="{{ route($model->route . '.edit', $imagable) }}" class="ui primary button">
                        <i class="pencil icon"></i>
                        {{ __('Edit') }}
                    </a>
                    <form action="{{ route($model->route . '.destroy', $imagable) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="ui primary basic button">
                            <i class="trash icon"></i>
                            {{ __('Delete') }}
                        </button>
                    </form>
                </div>
            @endcan
        </div> --}}
    </div>
</div>

@endsection