routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([ 'verify' => true ]);

Route::redirect('/home', '/');

Route::get('/', 'HomeController@index')->name('home');

Route::resources([
    'creations' => 'CreationController',
    'sketches' => 'SketchController',
    'challenges' => 'ChallengeController',
]);

// Comments
Route::resource('comments', 'CommentsController')
    ->only([ 'store', 'destroy' ]);
Route::get('{commentable_type}/{commentable_id}#comment:{comment}')
    ->name('comments.show');

// Responses
Route::resource('responses', 'ResponseController')
    ->only([ 'show', 'store', 'edit', 'update', 'destroy' ]);
Route::get('challenges/{challenge}/responses/create', 'ResponseController@create')
    ->name('responses.create');

// Users
Route::resource('users', 'UserController')
    ->except([ 'show' ]);
Route::get('{user}/togglefollow', 'UserController@toggleFollow')
    ->middleware('auth')
    ->name('users.togglefollow');
Route::post('/validate-username', 'UserController@validateUsername')
    ->middleware('auth');
Route::get('/{user}/notifications', 'UserController@notifications')
    ->middleware('auth')
    ->name('users.notifications');

// Folders
Route::resource('folders', 'FolderController')
    ->except([ 'index' ]);

// Push Subscriptions
Route::put('push-subscription', 'PushSubscriptionController@update');
Route::delete('push-subscription', 'PushSubscriptionController@destroy');

// User
Route::get('/{user}', 'UserController@show')
    ->name('users.show');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="manifest" href="/manifest.json">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- Icon --}}
    <link rel="icon" href="{{ asset('pictures/logo.jpg') }}">

    <title>
        @yield('header') - {{ config('app.name', 'Laravel') }}
    </title>

    <!-- Scripts -->
    <script>
        window.vapidPublicKey = "{{ config('webpush.vapid.public_key') }}"
    </script>
    <script src="{{ asset('js/jquery.js') }}"></script>
    <script src="{{ asset('js/throttle.js') }}"></script>
    <script src="{{ asset('js/autosize.min.js') }}"></script>
    <script src="{{ asset('js/lazyload.js') }}" defer async></script>
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/micon.min.css') }}">

    <!-- Styles -->
    {{-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> --}}
    {{-- <link href="{{ asset('semantic/dist/components/transition.min.css') }}" rel="stylesheet">
    <link href="{{ asset('semantic/dist/semantic.min.css') }}" rel="stylesheet"> --}}
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
</head>

<body class="min-h-screen bg-@yield('background', 'grey-lightest')">
    <div class="bg-grey-lightest p-6 md:p-8 flex flex-col md:flex-row justify-between sticky pin-t z-50 blurry transition" id="page-header">
        <div class="flex flex-row justify-between items-center">
            <div class="flex flex-col text-grey-darkest">
                <a href="/" class="text-xs md:text-base font-black" id="brand">
                    {{ config('app.name', 'Greymatter') }}
                </a>
                <div class="text-3xl md:text-5xl font-black">
                    @yield('header')
                </div>
            </div>
            <i class="text-3xl mi mi-GlobalNavButton md:hidden" id="hamburger-menu-icon"></i>
        </div>
        <div class="navigation">
            <a href="{{ route('home') }}" class="{{ starts_with(Route::currentRouteName(), 'home') ? 'active' : '' }} item">
                <i class="mi mi-Home"></i>
                <div class="content">
                    {{ __('Feed') }}
                </div>
            </a>

            <a href="{{ route('creations.index') }}" class="{{ starts_with(Route::currentRouteName(), 'creations') ? 'active' : '' }} item">
                <i class="mi mi-Photo2"></i>
                <div class="content">
                    {{ __('Creations') }}
                </div>
            </a>

            <a href="{{ route('sketches.index') }}" class="{{ starts_with(Route::currentRouteName(), 'sketches') ? 'active' : '' }} item">
                <i class="mi mi-Handwriting"></i>
                <div class="content">
                    {{ __('Sketches') }}
                </div>
            </a>

            <a href="{{ route('challenges.index') }}" class="{{ starts_with(Route::currentRouteName(), 'challenges') ? 'active' : '' }} item">
                <i class="mi mi-Communications"></i>
                <div class="content">
                    {{ __('Challenges') }}
                </div>
            </a>

            <a href="{{ route('users.index') }}" class="{{ starts_with(Route::currentRouteName(), 'users') ? 'active' : '' }} item">
                <i class="mi mi-Contact"></i>
                {{ __('Users') }}
            </a>
        </div>
        <div class="navigation">
            @guest
                <a class="{{ Route::currentRouteNamed('login') ? 'active' : '' }} item" href="{{ route('login') }}">
                    {{ __('Login') }}
                </a>
                <a class="{{ Route::currentRouteNamed('register') ? 'active' : '' }} item" href="{{ route('register') }}">
                    {{ __('Register') }}
                </a>
            @else
                <a href="{{ Auth::user()->route('notifications') }}" class="{{ ends_with(Route::currentRouteName(), 'notifications') ? 'active' : '' }} item">
                    <div class="{{ Auth::user()->unreadNotifications()->count() > 0 ? 'bg-orange rounded-full p-2 text-white font-bold' : '' }} flex flex-row items-center">
                        @if (Auth::user()->unreadNotifications()->count() > 0)
                            <i class="mi mi-Ringer mr-4"></i>
                            {{ Auth::user()->unreadNotifications()->count() }}
                        @else
                            <i class="mi mi-Ringer"></i>
                        @endif
                    </div>  
                </a>
                <a href="{{ Auth::user()->route('show') }}" class="item flex flex-row items-center loggedinuser">
                    <img src="{{ Auth::user()->avatar()->url() }}" alt="" class="w-auto h-8 shadow-md rounded-full">
                    <div class="font-bold text-grey-darker ml-4">
                        {{ Auth::user()->name }}
                    </div>
                </a>
            @endguest
        </div>
    </div>
    <div class="@yield('padding', 'md:px-8')">
        @if (Auth::user() && !Auth::user()->hasVerifiedEmail())
            <div class="mx-auto container my-8">
                @include('components.auth.verify')
            </div>
        @endif
        @yield('content')
    </div>
</body>
</html>

resources/views/layouts/notification.blade.php
<a href="{{ isset($link) ? $link : $subject->route() }}" class="flex flex-row items-start justify-start hover:bg-grey-lightest -mx-8 px-8 py-4 {{ $notification->unread() ? 'bg-blue-lightest' : '' }}">

    <img src="{{ isset($icon) ? $icon : $subject->user->avatar()->url() }}" class="rounded-full h-10 w-10 mr-4" alt="">

    <div class="flex flex-col items-start">
        <div class="font-bold">{{ $title }}</div>
        <div class="text-grey-darker mt-2">{{ $slot }}</div>
    </div>

</a>